name: Build and Deploy React App to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ca-central-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install React app dependencies
        working-directory: ./my-react-cdk-python-app/react_app
        run: npm ci

      - name: Build React app
        working-directory: ./my-react-cdk-python-app/react_app
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install CDK and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./my-react-cdk-python-app/requirements.txt
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Deploy
        working-directory: ./my-react-cdk-python-app
        run: cdk deploy --require-approval never